/** BOSS FIGHT GAMESTRINGS **/
/** Fight detail text **/
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,10,"The fake nest brought Old Willy into your trap, and now you have a metric ton of ticked-off prairie chicken to deal with. Thankfully, your Clan is here to provide backup. The up-close types are drawing Willy\'s attention while the riflemen and pistoleers are trying to find a spot to shoot that isn\'t covered with thick, tough hide. This could be a long fight, but if everybody pulls their weight, you will all be eating chicken tonight.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,10,"The earth rumbles, the blood flows, and the chicken squawks its horrific call. Old Willy is a tougher son-of-a-gun than you would have guessed, but, then again, that\'s probably how he got to be \'Old\' Willy in the first place. Some of your backup high-tailed it out of here when the going got rough, but if this bird is going in the bag, you\'ve got to keep the pressure on.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,10,"Old Willy has crowed his last sunrise. The people of Trailer Park will be able to sleep peacefully with the knowledge that the biggest, meanest prairie chicken in the Sector has gone to the great roost in the sky. Plus they know they paid you handsomely for the job. There are bigger and badder enemies out in the wilderness, but now it\'s just a matter of time before they meet Willy\'s end. Your Clan is going to have one hell of a victory bash tonight. The rotgut is on you.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,11,"You survived, but you still just lost a fight to a chicken.  This one is going to be tough to live down back at the bar.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,12,"boss_1_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (134,13,"boss_1_victory.jpg");



INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,10,"This seemed like a better idea in the planning stages. Thunder ripped out of the ground right from under you, knocking you and your team to the shifting ground. You didn\'t know sandworms even came in this size. The monster\'s roar can be heard for miles, which you hope will be enough to call in your reinforcements, especially since you lost track of your radio in all of the chaos. No time to think about that, though. If you don\'t act quickly, you\'re going to end up as worm food.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,10,"The ground shakes with every attack and your armor has a gash in it from Thunder\'s machete-sized fangs. Still, you\'re wearing him down. He\'s bleeding from a hundred bullet wounds and his movement has slowed. A scary thought occurs to you: If dead sandworm juice was enough to call this monster, and he\'s leaking all over the place, are you going to have any sandworm cavalry to worry about? No time to think about that. Stay the course, stick to the plan, and hopefully you\'ll live long enough to tell this whopper at the bar.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,10,"After suffering one final death-blow, Thunder rears back and bellows loud enough for the whole damned desert to hear. You and what\'s left of your backup scurry out from under the beast as it comes crashing down into the sand. The impact lifts you off your feet for just a second, but you keep your balance. Looking back at this dead worm, you congratulate yourself on a job well done.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,11,"The fight was a close one, but the ground you were standing on had just become too unstable to continue.  A hasty retreat was your only option.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,12,"boss_2_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (135,13,"boss_2_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,10,"You can\'t help but think that maybe you\'ve made a slight tactical error. You unlocked the cage and unleashed the sasquatch onto its White Crow creators. That occupied him for about ten seconds before he turned on you. Time to call in your reinforcements and move this beast back into the realm of myth.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,10,"You\'ve never seen such strength before. The monster tore into one of your mercs and peeled his armor back like a piece of fruit. His muscles roll and strain underneath his furry skin, and every time he howls, you see your short life flash before your eyes. That\'s getting annoying. Stupid White Crow. You\'ll make them pay. If you survive.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,10,"The sasquatch picks you up like you\'re a twig and screams in your face, its rancid breath pushing your cheeks back from the force. That\'s when you raise your guns and plug it twice in the face. The beast falls backward like a downed tree, and you use its body to cushion your fall. There. One bad idea sent back to the drawing board.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,11,"The beast was too much for you, but you managed to force it back into its cage.  A White Crow survivor ran off with the key.  You'll have to get it back to finish this.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,12,"boss_3_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (136,13,"boss_3_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,10,"After wading through a small army of her cultists, you finally find yourself eye-to-eye with the queen vampire herself, Mother Larissa. To her credit, she doesn\'t waste time trying to hypnotize you or serenade you with emo poetry. Instead, she just lunges for your jugular. You have to admit--that\'s a refreshing approach.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,10,"Mother Larissa earned her status as queen of the dead. She\'s tougher than steel and with half the personality. Even with reinforcements, you\'re not sure if you\'ve got the numbers to take her down. You\'ve lost some of your men, including the poor sap that showed up with only a wreath full of garlic, claiming he\'d act as \'support.\' She threw a mossy stone through his sternum.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,10,"Mother Larissa\'s dying shriek echoes off the stone archways, and then she stops moving. You can\'t help but be proud of yourself and of your team. They stepped up and killed a creature of legend. Before leaving the crypt, you pick up a hunk of wood and run it through Mother Larissa\'s heart, just to be sure.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,11,"You barely escaped the den of the vampires.  You\'ll have another chance, but for now it\'s just nice to see the sun.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,12,"boss_4_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (137,13,"boss_4_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,10,"You open fire on the monster, hoping that a well-placed shot will send you back to the bar early. No such luck. Your shot glances off the creature\'s leathery hide, and it turns its angry, yellow eyes to you. It\'s fast, impossibly fast. You barely have time to put in the call for reinforcements before it\'s on you. Aw, hell, it\'s going to be one of those fights.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,10,"As long as you live, you will never laugh about the chupacabra again. It\'s real, it\'s mad, and it wants to eat your face. Thankfully, your team showed up to lend a hand, or the LifeNet facility would be rebuilding your genetic code right this very moment. You didn\'t think anything could move this fast without an engine. ");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,10,"The chupacabra finally stops clawing at you and lies still on the ground. You lean against a tree and try to catch your breath. You aren\'t happy about living in an apocalypse that can create this kind of mutant. Fast, deadly, and easily annoyed. You only survived by putting it in the center of you and your team\'s firing zone and literally running circles around it. Someone needs to write that tactic down.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,11,"Whatever that thing was, it tore through your army like wet paper.  You have to regroup and rethink before you can take it on again.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,12,"boss_5_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (138,13,"boss_5_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,10,"Ursaline stands on his hind legs and roars. At full extension, he\'s at least 12 feet... maybe 15 feet...? Well, he\'s big; no question about that. No, the only question left is whether you have enough ammo to bring this big monster down.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,10,"You knew that bounty hunting in the waste would have days like this. You took a vicious swipe to your armor and found yourself falling back to the perimeter to manage your forces. Your Clan charges at the beast to try and whittle it down, but they take heavy casualties. You grab the radio and call in more. Numbers are your best weapon.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,10,"If every bear grew that big, and if every bear was this tough to kill, it would be their land you\'re living in. As it is, tactics and firepower won the day. For just a moment, you wonder about Ursaline\'s momma and poppa bear, but then put that thought out of your mind before it costs you a helping of sleepless nights.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,11,"And to think that kids used to carry toy versions of these things.  There's nothing cute or cuddly about getting your tail kicked, but that\'s just what happened.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,12,"boss_6_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (139,13,"boss_6_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,10,"Super-soldier, huh? Well, that makes sense. He stands over nine feet tall and he\'s got some kind of giant weapon in his hands. Whoa, is that a helicopter blade? Probably a good idea to stay out of reach and fire away, but your bullets bounce off his skin. Yep, he\'s \'super\' all right. Yet he doesn\'t appear bright enough, or agreeable enough, to follow orders. Good thing you and your Clan can. This might be the only advantage you get.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,10,"You count down the ways this fight is going wrong. You\'ve lost some good men and too many clips of ammo. And he picked off some of your long-range fighters with one swing of his helicopter blade. Now the good news: You\'ve managed to lure him outside, giving your team more room to maneuver. Plus, you found that some high-powered rifle shots get through his skin. That\'s progress.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,10,"Now you know why residents were afraid of Pamela Hunter and her experiments. A chill goes through your guts at the thought of monsters like this being mass-produced on a genetic assembly line. You have a feeling that nobody would suffer worse than Pamela, because this is one army that can\'t be controlled. Thankfully, they can be killed.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,11,"Maybe you should have started with Test Subject 1.  Jumping ahead to 42 just got you a headache and a few dead friends.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,12,"boss_7_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (140,13,"boss_7_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,10,"So far in your career, you\'ve battled giant mutant chickens, wannabe vampires, and every other kind of monster you could have imagined, but you never could have predicted this. In the center of the Brigg\'s Point facility is a gargantuan beast! It\'s got the shell of an armadillo and a mouth full of jagged razors. More than anything, it resembles a dragon. One of your mercs calls it El Cadejo, and El Cadejo is looking at you. Fight or die.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,10,"El Cadejo lifts its massive paw and folds it into a fist, then brings it down over your head. You just barely dodge, firing wildly. It\'s tough to aim while on the run, but thankfully the monster is just about as big as a barn. You call out on the radio for every available man. You can\'t leave anything in reserve. Not this time.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,10,"El Cadejo wheezes its final breath and lies still. You can\'t resist the urge to climb the conquered creature and play king of the hill. Brigg\'s Point is yours, and you earned that prize by defeating a legend. ");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,11,"You managed to escape, but you can't decide if that\'s because you\'re that good, or if the monster was just too gorged on your less fortunate teammates to chase you.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,12,"boss_8_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (141,13,"boss_8_victory.jpg");

INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,10,"Stage one of the fight isn\'t working out as planned. You had thought that a nice killing circle would bring the monster down quickly; instead, it broke through your ranks and is now chasing your troops around the woods. The experience should make them feel truly alive. Unless it kills them.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,10,"The running of the patriarch has gone on long enough. You grab a blood-stained shirt from the body of a fallen merc and whip it at the patriarch as it runs past you. The beast skids to a stop, digging deep grooves into the earth. It turns around and stares you down, pawing its club-like foot into the dirt. It charges, but you don\'t have the time to reconsider your options. You flick the shirt to the right and then dodge left. If you can distract him like this long enough, your friends can finish him off.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,10,"The patriarch kneels and then collapses, a dozen spears and sabers jutting out from his back. You\'ve done your job and earned your reward. Now, where is the best place to cut a steak off this thing?");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,11,"You feel too queasy to continue, probably an overdose of radiation from putting together the bait.  You have to let the bull have its way this time, but there\'s always next time.");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,12,"boss_9_defeat.jpg");
INSERT INTO fw_gamestrings (itemid, itemtype, gamestring) VALUES (142,13,"boss_9_victory.jpg");